name: Helm OCI Chart Releaser
description: Push Helm charts to OCI-based registries
author: sergeyshaykhullin
branding:
  color: orange
  icon: package
inputs:
  image:
    required: true
    description: Chart name
  repository:
    required: true
    description: Chart repository name
  tag:
    required: true
    description: Chart version
  path:
    required: false
    description: Chart path
    default: charts
  registry:
    required: true
    description: OCI registry
  registry_username:
    required: true
    description: OCI registry username
  registry_password:
    required: true
    description: OCI registry password
runs:
  using: composite
  steps:
    - name: Helm | Login
      shell: bash
      run: echo ${{ inputs.registry_password }} | helm registry login -u ${{ inputs.registry_username }} --password-stdin ${{ inputs.registry }}
      env:
        HELM_EXPERIMENTAL_OCI: "1"

    - name: Helm | Chart
      shell: bash
      run: helm chart save $PATH ${{ inputs.registry }}/${{ inputs.repository }}/${{ inputs.image }}:${{ inputs.tag }}
      env:
        HELM_EXPERIMENTAL_OCI: "1"
        PATH: ${{ inputs.path == 'charts' && format('{0}/{1}', inputs.path, inputs.image) || inputs.path }}

    - name: Helm | Chart | Push
      shell: bash
      run: helm chart push ${{ inputs.registry }}/${{ inputs.repository }}/${{ inputs.image }}:${{ inputs.tag }}
      env:
        HELM_EXPERIMENTAL_OCI: "1"
