name: Helm OCI Chart Releaser
description: "Push Helm charts to OCI-based registries"
author: "sergeyshaykhullin"
branding:
  color: orange
  icon: package
inputs:
  image:
    required: true
    description: ""
  repository:
    required: true
    description: ""
  tag:
    required: true
    description: ""
  path:
    required: false
    description: ""
    default: charts
  registry:
    required: true
    description: ""
  registry_username:
    required: true
    description: ""
  registry_password:
    required: true
    description: ""
# TODO:
# outputs:
runs:
  using: composite
  steps:
    - name: Helm | Login
      id: helm_login
      shell: bash
      run: echo ${{ inputs.registry_password }} | helm registry login -u ${{ inputs.registry_username }} --password-stdin ${{ inputs.registry }}

    - name: Helm | Chart
      id: helm_chart
      shell: bash
      run: helm chart save ${{ inputs.path }} ${{ inputs.registry }}/${{ inputs.repository }}/${{ inputs.image }}:${{ inputs.tag }}

    - name: Helm | Chart | Push
      id: helm_chart_push
      shell: bash
      run: helm chart push ${{ inputs.registry }}/${{ inputs.repository }}/${{ inputs.image }}:${{ inputs.tag }}
