name: Helm OCI Chart Releaser
description: Push Helm charts to OCI-based registries
author: sergeyshaykhullin
branding:
  color: orange
  icon: package
inputs:
  image:
    required: true
    description: Chart name
  repository:
    required: true
    description: Chart repository name
  tag:
    required: true
    description: Chart version
  path:
    required: false
    description: Chart path
    default: charts
  registry:
    required: true
    description: OCI registry
  registry_username:
    required: true
    description: OCI registry username
  registry_password:
    required: true
    description: OCI registry password
# TODO:
# outputs:
runs:
  using: composite
  steps:
    - name: Helm | Login
      id: helm_login
      shell: bash
      run: echo ${{ inputs.registry_password }} | helm registry login -u ${{ inputs.registry_username }} --password-stdin ${{ inputs.registry }}
      env:
        HELM_EXPERIMENTAL_OCI: "1"

    - name: Helm | Chart
      id: helm_chart
      shell: bash
      # TODO: ${{ inputs.path }} charts/image
      run: helm chart save ${{ inputs.path }} ${{ inputs.registry }}/${{ inputs.repository }}/${{ inputs.image }}:${{ inputs.tag }}
      env:
        HELM_EXPERIMENTAL_OCI: "1"

    - name: Helm | Chart | Push
      id: helm_chart_push
      shell: bash
      # TODO: ${{ inputs.path }} charts/image
      run: helm chart push ${{ inputs.registry }}/${{ inputs.repository }}/${{ inputs.image }}:${{ inputs.tag }}
      env:
        HELM_EXPERIMENTAL_OCI: "1"
